apiVersion : v2
name       : deploy-everythink
type       : application
version    : 1.0.0


keywords:
  - deployment
  - service
  - route
  - configmap
  - secret


maintainers:
  - name : Valentin Kozlov