apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.imageName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ default "8080" .Values.service.port }}
      protocol: TCP
      targetPort: main
  selector:
    {{- include "labels" . | nindent 4 }}
  type: ClusterIP