apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
  type: NodePort
  ports:
  - name: postgresql
    port: {{ .Values.service.port }}
    targetPort: 5432
    nodePort: {{ .Values.service.nodePort }}
