apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: postgresql
        image: {{ .Values.image.registry }}/{{ .Values.image.imageName }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
        env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        ports:
        - name: postgresql
          containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "{{ .Values.statefullset.persistence.storageClass }}"
      resources:
        requests:
          storage: {{ .Values.statefullset.persistence.size }}
